### ISSUE TITLE
git submodule update fails

### ISSUE THREAD

**Issue by grammoboy2** [ajboni/calvo#34]
Not the right permissions

Do I need to install - [blessed](https://github.com/chjj/blessed) for the UI?
It's not a package that is in Debian/Ubuntu right?

**Comment by ajboni** [comment]
> Not the right permissions
> 
> Do I need to install - [blessed](https://github.com/chjj/blessed) for the UI?
> It's not a package that is in Debian/Ubuntu right?

Hi! Thanks for trying calvo! Dependencies for this project are a bit complicated. We have:

OS Deps: 
- JACK
- jalv (this one is tricky because its not on kxrepos or ubuntu)
- lilv (this one is tricky because its not on kxrepos or ubuntu)
- nodejs
- Python

Python Deps: 
- Calvo Cli Tools (https://github.com/ajboni/calvo-cli-tools)  this is added as a git submodule. My thought is that this is failing for some reason
```
[submodule "py/calvo_cli_tools"]
	path = py/calvo_cli_tools
	url =  git@github.com:ajboni/calvo-cli-tools.git
```

Node deps: A lot, but should be autoinstalled with `npm install` including blessed. Hope it helps

Do you get any error message?

**Comment by grammoboy2** [comment]
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:ajboni/calvo-cli-tools.git' into submodule path '/home/debian/myhome/develop/calvo/py/calvo_cli_tools' failed
Failed to clone 'py/calvo_cli_tools'. Retry scheduled
Cloning into '/home/debian/myhome/develop/calvo/py/calvo_cli_tools'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:ajboni/calvo-cli-tools.git' into submodule path '/home/debian/myhome/develop/calvo/py/calvo_cli_tools' failed
Failed to clone 'py/calvo_cli_tools' a second time, aborting

**Comment by ajboni** [comment]
if you can't use ssh, you can change .gitmodules to use https:
https://github.com/ajboni/calvo-cli-tools

```
[submodule "py/calvo_cli_tools"]
	path = py/calvo_cli_tools
	url =  git@github.com:ajboni/calvo-cli-tools.git
```

change to


```
[submodule "py/calvo_cli_tools"]
	path = py/calvo_cli_tools
	url =  https://github.com/ajboni/calvo-cli-tools.git
```
I think I can cahnge it to deafult if that fix it

**Comment by grammoboy2** [comment]
didn't fix it. Same error.

**Comment by ajboni** [comment]
I've update the submodules and readme, can you try again from scratch cloning in a new folder? thanks

**Comment by grammoboy2** [comment]
Solved, thx. Now I've to figure out how to get npm...

**Comment by ajboni** [comment]
> Solved, thx. Now I've to figure out how to get npm...

Great , good luck! dependencies are a pain in this project tbh.

**Comment by grammoboy2** [comment]
Which dependencies are the pain? Lilv is installed here.
